### ISSUE TITLE
CI Checklist 

### ISSUE THREAD

**Issue by agritheory** [agritheory/cloud_storage#2]
- [x] Validate JSON and Python Syntax [example](https://github.com/agritheory/check_run/blob/version-13/.github/workflows/main.yml)
- [x] Black (frappe/black) + precommit
- [x] mypy
- [x] Prettier (use stonecrop config) + precommit
- [x] Unit tests
- [x] Semantic Release
